param(
    [string]$SourceCommit = 'bfcdd67a88b5c3412879d8680e7b101e59b352f5',
    [string]$LicenseCommit = '4178770badecb1b349fbcd62c737e0d7a2079729'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$projectRoot = Split-Path -Parent $PSScriptRoot
$assetDirectory = Join-Path $projectRoot 'backend\assets'
$licenseDirectory = Join-Path $projectRoot 'licenses\rules'
$snapshotPath = Join-Path $assetDirectory 'mihomo-rules-inline.yaml'
$manifestPath = Join-Path $assetDirectory 'mihomo-rules-manifest.json'
$licensePath = Join-Path $licenseDirectory 'MetaCubeX-meta-rules-dat-GPL-3.0.txt'
$downloadDirectory = Join-Path ([System.IO.Path]::GetTempPath()) 'sublinkx-mihomo-rule-update'
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

$providers = @(
    [pscustomobject]@{ Name = 'private_domain'; Behavior = 'domain'; Path = 'geo/geosite/private.yaml' }
    [pscustomobject]@{ Name = 'private_ip'; Behavior = 'ipcidr'; Path = 'geo/geoip/private.yaml' }
    [pscustomobject]@{ Name = 'ai'; Behavior = 'domain'; Path = 'geo/geosite/category-ai-!cn.yaml' }
    [pscustomobject]@{ Name = 'github_domain'; Behavior = 'domain'; Path = 'geo/geosite/github.yaml' }
    [pscustomobject]@{ Name = 'youtube_domain'; Behavior = 'domain'; Path = 'geo/geosite/youtube.yaml' }
    [pscustomobject]@{ Name = 'google_domain'; Behavior = 'domain'; Path = 'geo/geosite/google.yaml' }
    [pscustomobject]@{ Name = 'telegram_domain'; Behavior = 'domain'; Path = 'geo/geosite/telegram.yaml' }
    [pscustomobject]@{ Name = 'telegram_ip'; Behavior = 'ipcidr'; Path = 'geo/geoip/telegram.yaml' }
    [pscustomobject]@{ Name = 'netflix_domain'; Behavior = 'domain'; Path = 'geo/geosite/netflix.yaml' }
    [pscustomobject]@{ Name = 'netflix_ip'; Behavior = 'ipcidr'; Path = 'geo/geoip/netflix.yaml' }
    [pscustomobject]@{ Name = 'bilibili_domain'; Behavior = 'domain'; Path = 'geo/geosite/bilibili.yaml' }
    [pscustomobject]@{ Name = 'spotify_domain'; Behavior = 'domain'; Path = 'geo/geosite/spotify.yaml' }
    [pscustomobject]@{ Name = 'steam_domain'; Behavior = 'domain'; Path = 'geo/geosite/steam.yaml' }
    [pscustomobject]@{ Name = 'paypal_domain'; Behavior = 'domain'; Path = 'geo/geosite/paypal.yaml' }
    [pscustomobject]@{ Name = 'onedrive_domain'; Behavior = 'domain'; Path = 'geo/geosite/onedrive.yaml' }
    [pscustomobject]@{ Name = 'microsoft_domain'; Behavior = 'domain'; Path = 'geo/geosite/microsoft.yaml' }
    [pscustomobject]@{ Name = 'apple_domain'; Behavior = 'domain'; Path = 'geo/geosite/apple.yaml' }
    [pscustomobject]@{ Name = 'apple_ip'; Behavior = 'ipcidr'; Path = 'geo-lite/geoip/apple.yaml' }
    [pscustomobject]@{ Name = 'geolocation-not-cn'; Behavior = 'domain'; Path = 'geo-lite/geosite/proxy.yaml' }
    [pscustomobject]@{ Name = 'cn_domain'; Behavior = 'domain'; Path = 'geo-lite/geosite/cn.yaml' }
    [pscustomobject]@{ Name = 'cn_ip'; Behavior = 'ipcidr'; Path = 'geo-lite/geoip/cn.yaml' }
    [pscustomobject]@{ Name = 'tracker_domain'; Behavior = 'domain'; Path = 'geo/geosite/tracker.yaml' }
    [pscustomobject]@{ Name = 'private_tracker_domain'; Behavior = 'domain'; Path = 'geo/geosite/category-pt.yaml' }
)

New-Item -ItemType Directory -Path $assetDirectory -Force | Out-Null
New-Item -ItemType Directory -Path $licenseDirectory -Force | Out-Null
New-Item -ItemType Directory -Path $downloadDirectory -Force | Out-Null

$snapshotLines = [System.Collections.Generic.List[string]]::new()
$snapshotLines.Add('# Generated by scripts/update-mihomo-rules.ps1. Do not edit manually.')
$snapshotLines.Add("# Source: https://github.com/MetaCubeX/meta-rules-dat/tree/$SourceCommit")
$manifestProviders = [System.Collections.Generic.List[object]]::new()

foreach ($provider in $providers) {
    $downloadPath = Join-Path $downloadDirectory ($provider.Name + '.yaml')
    $sourceUrl = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/$SourceCommit/$($provider.Path)"
    Invoke-WebRequest -Uri $sourceUrl -OutFile $downloadPath -UseBasicParsing

    $sourceLines = @(Get-Content -LiteralPath $downloadPath -Encoding UTF8)
    if ($sourceLines.Count -lt 2 -or $sourceLines[0] -ne 'payload:') {
        throw "规则源格式异常：$($provider.Path) 缺少 payload 列表。"
    }

    $payloadLines = @($sourceLines | Select-Object -Skip 1 | Where-Object { $_.Length -gt 0 })
    $invalidLines = @($payloadLines | Where-Object { $_ -notmatch '^    - .+' })
    if ($payloadLines.Count -eq 0 -or $invalidLines.Count -gt 0) {
        throw "规则源格式异常：$($provider.Path) 包含空列表或无法安全合并的行。"
    }

    $snapshotLines.Add("$($provider.Name):")
    $snapshotLines.Add('  type: inline')
    $snapshotLines.Add("  behavior: $($provider.Behavior)")
    $snapshotLines.Add('  payload:')
    foreach ($line in $payloadLines) {
        $snapshotLines.Add($line)
    }

    $manifestProviders.Add([ordered]@{
        name = $provider.Name
        behavior = $provider.Behavior
        source_path = $provider.Path
        source_url = $sourceUrl
        payload_entries = $payloadLines.Count
        sha256 = (Get-FileHash -LiteralPath $downloadPath -Algorithm SHA256).Hash.ToLowerInvariant()
    })
}

[System.IO.File]::WriteAllText($snapshotPath, (($snapshotLines -join "`n") + "`n"), $utf8NoBom)

$manifest = [ordered]@{
    project = 'MetaCubeX/meta-rules-dat'
    project_url = 'https://github.com/MetaCubeX/meta-rules-dat'
    source_commit = $SourceCommit
    license = 'GPL-3.0-only'
    license_commit = $LicenseCommit
    checked_at = [DateTime]::UtcNow.ToString('yyyy-MM-dd')
    transformation = 'Selected common YAML payload lists, including geo-lite CN/proxy sets, are merged into Mihomo inline rule-providers without changing entries.'
    providers = $manifestProviders
}
$manifestJson = $manifest | ConvertTo-Json -Depth 6
[System.IO.File]::WriteAllText($manifestPath, ($manifestJson + "`n"), $utf8NoBom)

$licenseUrl = "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/$LicenseCommit/LICENSE"
Invoke-WebRequest -Uri $licenseUrl -OutFile $licensePath -UseBasicParsing
$licenseText = Get-Content -LiteralPath $licensePath -Raw -Encoding UTF8
[System.IO.File]::WriteAllText($licensePath, $licenseText, $utf8NoBom)

$snapshotHash = (Get-FileHash -LiteralPath $snapshotPath -Algorithm SHA256).Hash.ToLowerInvariant()
Write-Host "Mihomo inline rules updated: $($providers.Count) providers"
Write-Host "Snapshot: $snapshotPath"
Write-Host "SHA-256: $snapshotHash"
